### 🧑‍🏫 NumPy Lesson Plan (Beginner → AI-ready)

#### 1. Introduction to NumPy

📌 Explain: NumPy is the foundation of numerical computing in Python. It provides fast arrays (like lists, but optimized in C). Almost all AI libraries (TensorFlow, PyTorch, Scikit-learn) use NumPy under the hood.

In [1]:
import numpy as np

# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

# Create a 2D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


#### 2. Array Attributes

📌 Show how arrays store shape, size, and data type.

In [2]:
print("Shape:", arr2.shape)   # (2, 3)
print("Size:", arr2.size)     # 6
print("Data type:", arr2.dtype)

Shape: (2, 3)
Size: 6
Data type: int32


#### 3. Array Creation

📌 Common ways to create arrays for ML tasks.

In [ ]:
# Zeros and ones
zeros = np.zeros((2, 3))
ones = np.ones((3, 3))
print("Zeros:\n", zeros)
print("Ones:\n", ones)

# Range of numbers
arr = np.arange(0, 10, 2)  # start, stop, step
print("Arange:", arr)

# Random numbers (useful in AI for initialization)
rand = np.random.rand(2, 3)  # uniform random [0,1)
print("Random:\n", rand)

#### 4. Indexing & Slicing

📌 Important for selecting parts of data (like choosing features).

In [3]:
arr = np.array([10, 20, 30, 40, 50])

print("First element:", arr[0])
print("Last element:", arr[-1])
print("Slice [1:4]:", arr[1:4])

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Element at (1,2):", matrix[1, 2])   # row 1, col 2
print("First row:", matrix[0, :])
print("First column:", matrix[:, 0])

First element: 10
Last element: 50
Slice [1:4]: [20 30 40]
Element at (1,2): 6
First row: [1 2 3]
First column: [1 4 7]


#### 5. Vectorized Operations

📌 NumPy lets you do math on whole arrays (fast + concise).

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Add:", a + b)
print("Multiply:", a * b)
print("Dot product:", np.dot(a, b))  # 1*4 + 2*5 + 3*6
print("Mean:", np.mean(a))

Add: [5 7 9]
Multiply: [ 4 10 18]
Dot product: 32
Mean: 2.0


#### 6. Broadcasting

📌 Powerful feature: small arrays expand to match big ones.

In [5]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])

print("Matrix:\n", matrix)
print("Vector:", vector)

print("Broadcasted addition:\n", matrix + vector)

Matrix:
 [[1 2 3]
 [4 5 6]]
Vector: [10 20 30]
Broadcasted addition:
 [[11 22 33]
 [14 25 36]]


#### 7. Linear Algebra (AI Connection 🚀)

📌 Linear algebra is the backbone of ML.

In [ ]:
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

# A:
#     1, 2
#     3, 4
# B:
#     2, 0
#     1, 2

# dot:
#     1 2  dot product  2 0  results in:  4  4
#     3 4        *      1 2               10 8

print("Matrix multiplication:\n", np.dot(A, B))

# Transpose
print("Transpose:\n", A.T)

# Determinant
print("Determinant:", np.linalg.det(A))

# Inverse
print("Inverse:\n", np.linalg.inv(A))

Matrix multiplication:
 [[ 4  4]
 [10  8]]
Transpose:
 [[1 3]
 [2 4]]
Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


#### 8. Mini-Project: Cosine Similarity (Basic AI Concept)

📌 Used in NLP & recommendation systems. Measures how similar two vectors are.

In [7]:
def cosine_similarity(vec1, vec2):
    dot = np.dot(vec1, vec2)
    norm1 = np.linalg.norm(vec1)
    norm2 = np.linalg.norm(vec2)
    return dot / (norm1 * norm2)

v1 = np.array([1, 2, 3])
v2 = np.array([2, 3, 4])

print("Cosine similarity:", cosine_similarity(v1, v2))

Cosine similarity: 0.9925833339709303


#### 9. Challenge Exercises for Students

- Create a 5×5 matrix of random numbers and find:

    - The mean of all elements

    - The max of each row

    - The sum of each column

- Implement a normalize(vector) function that scales a vector to unit length.

- Represent two 2D points as vectors → calculate the Euclidean distance between them.

In [8]:
def euclidean_distance(p1, p2):
    return np.linalg.norm(p1 - p2)

p1 = np.array([1, 2])
p2 = np.array([4, 6])
print("Euclidean distance:", euclidean_distance(p1, p2))

Euclidean distance: 5.0
